apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudexport-ingress
  namespace: cloudexport
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "2000m"
    nginx.ingress.kubernetes.io/websocket-services: cloudexport-api
spec:
  rules:
    - host: api.cloudexport.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cloudexport-api
                port:
                  number: 80
