apiVersion: v1
kind: Secret
metadata:
  name: cloudexport-secrets
  namespace: cloudexport
type: Opaque
data:
  S3_ACCESS_KEY_ID: bWluaW9hZG1pbg==
  S3_SECRET_ACCESS_KEY: bWluaW9hZG1pbg==
  JWT_SECRET: Y2hhbmdlLW1l
  BOOTSTRAP_API_KEY: Y2xvdWRleHBvcnQtZGV2LWtleQ==
